title: Good Shit!
author: dewittg
email: dewitt@hallsonic.com
theme: minima # theme changed to minima
description: > # this means to ignore newlines until "baseurl:"
  This is where the good shit lives!

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  dewittg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
