title: Good Shit!
theme: minima
author: dewitt4
email: dewitt@hallsonic.com
description: > # this means to ignore newlines until "baseurl:"
  This is a basic test pagae that I made using Github Pages tutorials that should should help people really appreciate good shit!
# social links
twitter_username: your-twitter-handle none # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle dewittg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
